### ISSUE TITLE
SOTA HTTPS deployment

### ISSUE THREAD

**Issue by ypid** [volkszaehler/volkszaehler.org#505] opened 2016-10-28 14:00 UTC
For volkszaehler.org and demo.volkszaehler.org

* https://www.ssllabs.com/ssltest/analyze.html?d=demo.volkszaehler.org
* https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fdemo.volkszaehler.org%2Ffrontend%2F
* https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fvolkszaehler.org%2F

HTTPS with Let's Encrypt could probably be tested on volkszaehler.org and when the cert for demo.volkszaehler.org expires, it could also be covered by Let's Encrypt using a SANs cert (one certificate for multiple hosts/domains).

Related to: #504

**Comment by andig** [comment] 2016-10-28 14:40
Duplicate of https://github.com/volkszaehler/volkszaehler.org/issues/370

**Closed by andig** 2016-10-28 14:40 UTC

**Comment by ypid** [comment] 2016-10-28 14:44
@andig Not really a duplicate but definitely related to #370. This issue includes #370 but has a few extra points. You could have leaved it open or reopen.
