### ISSUE TITLE
Network Error when opening index.html

### ISSUE THREAD

**Issue by bbr111** [volkszaehler/volkszaehler.org#849] opened 2021-03-25 22:22 UTC
when opening index.html

following error is shown:

NETWORK ERROR

https://demo.volkszaehler.org/middleware.php/entity.json?unique=1616710711906:

error

I tried to delete all cookie for this site and also tried to start inkognito windows.
But always the same error.
What can I do to prevent this? It look like the systems is trying to open fetch some data from this site. But this site is not available.

Browsers tried: MS Edge (Full Error Message), Chrome (only Network Error /error), Firefox (only Network Error /error)

**Comment by r00t-** [comment] 2021-03-25 23:26
duplicate of https://github.com/volkszaehler/volkszaehler.org/issues/848

**Closed by r00t-** 2021-03-25 23:26 UTC
