### ISSUE TITLE
No MIN MAX AVG CUR values on item in different groups 

### ISSUE THREAD

**Issue by Feilner** [volkszaehler/volkszaehler.org#669] opened 2018-02-28 22:07 UTC
I have some items in more than one group.
The MIN MAX AVG CUR values are only shown on the first item. No matter if first item ist visible (group is opened) or not.

See Picture e.g. for the "TempSoll EG Esszimmer"

![bildschirmfoto 2018-02-28 um 23 01 49](https://user-images.githubusercontent.com/6040107/36815597-817a0f7c-1cdb-11e8-8271-44308befbdf0.png)

**Comment by andig** [comment] 2018-03-05 10:08
Could you check if the issue is resolved in my development repo (https://github.com/andig/volkszaehler.org, next branch)? It already includes a bunch of fixes and new features that have not yet been merged.

**Comment by Feilner** [comment] 2018-03-05 18:38
Hello AndiG,

yes the issue is solved on your branch!

Do you have a time plan when your branch is integraded into the master?

Best regards,

Oliver

**Comment by andig** [comment] 2018-03-05 19:02
Not currently. You can continue using that branch if you want.

**Comment by andig** [comment] 2019-03-21 11:19
Should be fixed by recent merges into master.

**Closed by andig** 2019-03-21 11:19 UTC
Labels: Bug, Ready for Test
